grocy/grocy

localization/no.php
Updated norwegian localization for version 1.16.0
=> Updated for Version 1.16.0

.dockerignore, Dockerfile-grocy, Dockerfile-grocy-nginx, README.md, config-dist.php, docker-compose.yml, docker_nginx/common.conf, docker_nginx/conf.d/default.conf, docker_nginx/conf.d/ssl.conf, docker_nginx/nginx.conf, info.php
Hi Berrnd. Awesome job with Grocy. This PR allows anyone to run a dockerized version of Grocy.
=> Grocy docker patch

controllers/StockApiController.php, grocy.openapi.json, routes.php, services/StockService.php
At some point in the future I plan on making small Android app that would just allow quick scanning of all items via phone's camera after coming from the store.
For that, API needs to have a way to retrieve product by barcode.
I've almost no experience in PHP so far, so please criticize as much as you want.
=> Add fetch by barcode API method

config-dist.php, controllers/SystemController.php
Hi.
I wanted to changed the default view to the shopping list instead of the stock overview. After a little bit thinking i thought why not make in configurable. 
This PR introduces a new Setting "GROCY_ENTRY_PAGE" which can be set to any of the available features. (stock,shoppinglist, .......)
This will close #294.
=> Allow possibility to choose custom homepage

controllers/StockApiController.php, grocy.openapi.json, routes.php, services/StockService.php
This adds an API call, so a shopping list item can easily be removed
Please note: This is **UNTESTED**, as I was unable to run the current grocy master commit on my server.
=> Add API call to remove an item from the shopping list by productid

controllers/StockApiController.php, grocy.openapi.json, routes.php, services/StockService.php
Adds an API call to add items to a shoppinglist
=> Add API call for adding products to shoppinglist

helpers/extensions.php
Hello,
I propose a coorection for the issue https://github.com/grocy/grocy/issues/346
thanks
Fixes #346.
=> Parse settings provided via environment variables as boolean if needed

public/viewjs/mealplan.js
=> public mealplan: add fullscreen recipe in new tab (fixes #367)

views/components/barcodescanner.blade.php
=> Fixed #378

controllers/CalendarApiController.php, services/CalendarService.php
Adjustment to include description with a link to the meal plan in the calendar event.
fix #368
=> Calendar descriptions (iCal export)

grocy.openapi.json, routes.php
Changed line 173 to /stock/barcodes/external-lookup/{barcode} fixes grocy/grocy#456
=>  ExternalBarcodeLookup

controllers/StockApiController.php, controllers/StockController.php, grocy.openapi.json, localization/en/stock_transaction_types.po, localization/stock_transaction_types.pot, localization/strings.pot, migrations/0095.sql, public/viewjs/consume.js, public/viewjs/inventory.js, public/viewjs/purchase.js, public/viewjs/stockdetail.js, public/viewjs/stockedit.js, public/viewjs/stockoverview.js, public/viewjs/transfer.js, routes.php, services/StockService.php, views/components/productcard.blade.php, views/consume.blade.php, views/inventory.blade.php, views/layout/default.blade.php, views/purchase.blade.php, views/recipeposform.blade.php, views/stockdetail.blade.php, views/stockedit.blade.php, views/stockjournal.blade.php, views/stockoverview.blade.php, views/transfer.blade.php
=> Stock Service Updates

public/viewjs/mealplan.js
=> Check for Price Tracking in mealplan.js

controllers/StockApiController.php, grocy.openapi.json, public/viewjs/stockdetail.js, public/viewjs/stockedit.js, routes.php, services/StockService.php, views/stockdetail.blade.php
#488 fix
Take a look at the removal of stock and feel free to make further updates as desired.
=> Stock detail updates

public/viewjs/components/productcard.js
=> productcard.js check null location

public/viewjs/consume.js, public/viewjs/inventory.js, public/viewjs/purchase.js, public/viewjs/transfer.js
=> refresh productcard on save

grocy.openapi.json, services/StockService.php
The response of the call '/api/stock' now returns a new attribute
('product') which contains the details of the related product.
Created new pull request after discussion with previous PR to keep things clean.
Closes #487.
=> Feature request : api/stock can return detailed products #487

migrations/0095.sql, public/viewjs/recipeform.js, services/RecipesService.php, views/recipeform.blade.php, views/recipes.blade.php
#374 
Initial work for self producing products.
A product can be assigned to a recipe. On recipe consumption the product is created using the price of the recipe along with desired servings.
An idea is perhaps on recipe consumption a checkbox could toggle the creation of the product?
=> recipes can create products

public/viewjs/mealplan.js
#450 add consume product in meal plan
Thanks for flushing out the add product to the meal plan!
I had this part mostly done already and had a few minutes to work in a commit which just leaves adding the product to the shopping cart.
=> 450 consume meal plan product

public/viewjs/mealplan.js, services/CalendarService.php
#450 
Added the new notes and products to the calendar service
prevented seeing "undefined" on meal plans when no week is available
disabled week recipe consume if weekCosts are zero
=> 450 updates

views/batteriesoverview.blade.php
variable name bugfix & typo fix
=> Battery fix

services/CalendarService.php
Reflect flags in config option for calender service getevents
=> CalendarService reflect config options for GetEvents

views/recipes.blade.php
Include a hint on the recipeCard to see the base servings.
=> View base servings on recipecard

config-dist.php, public/css/grocy.css, public/viewjs/components/barcodescanner.js
This pull request enhances the display of the camera barcode scanner. The video frame size fits now in the viewport on mobile devices.
Additionally there's a feature toggle to automatically switch on the torch, if a camera barcode scanner is opened.
=> Camera barcode scanner enhancements

data/plugins/DemoBarcodeLookupPlugin.php
the DemoBarcodeLookupPlugin has the wrong API Endpoint in the Comment
=> fix api endpoint url in comment

public/viewjs/inventory.js, public/viewjs/purchase.js, public/viewjs/stockentryform.js
fixes #685
Maybe someone, with the feature enabled, can take a look if it's still working as expected.
=> Fix errors with disabled feature flag STOCK_PRICE_TRACKING

middleware/SessionAuthMiddleware.php, routes.php
See: https://github.com/slimphp/Slim/issues/2667#issuecomment-529901032
Fixes #696
=> PSR7-decoupled rework of authentication fixup

services/LocalizationService.php
=> Fixup: paths for localization file existence checks

public/viewjs/components/barcodescanner.js
I have added a button to pick what camera to scan with. The preferred camera ID is saved in local browser storage, so it is persisted for a reasonable amount of time. No change to default behaviour has been made, so the initial camera choice is still determined by the Quagga constraints.
I have two primary reasons for adding this button:
1. A lot of newer phones have a frightening amount of cameras on the back. On my own Galaxy S10, Quagga chose the 0.5x landscape camera by default. This camera has no autofocus and distorts the image, making it very bad for barcode scanning.
2. In the future I'd like to be able to hang a tablet on the fridge and use the front camera for scanning barcodes.
Here are a couple of screenshots of the proposed change:
1. Using the back camera
2. After clicking …
=> Add camera picker button

localization/strings.pot, public/css/grocy.css, public/viewjs/recipeform.js, views/components/numberpicker.blade.php, views/components/productpicker.blade.php, views/recipeform.blade.php, views/recipes.blade.php
=> Recipe Pages UI updates

public/css/grocy.css, public/viewjs/calendar.js, services/CalendarService.php
This allows the user to Click on a Calendar Event and be directed to the page that corresponds with that event
=> Link to respective page on Calendar Event Click

public/viewjs/quantityunitconversionform.js, views/quantityunitconversionform.blade.php
Fixes #388 
When creating a QU conversion there is a new checkbox to offer creating the inverse.
Editing QU Conversions would require some refactoring or much more in depth updates.
=> Create Inverse QU Conversions

controllers/RecipesController.php, public/css/grocy.css, public/viewjs/recipeform.js, public/viewjs/recipes.js, views/recipeform.blade.php, views/recipes.blade.php
- Update UI of Recipe Card
- Update UI of Gallery Cards
- Update logic for recipe creation - Only creates recipe once saved
- Update Recipe controller logic
Fixes: #787
=> Recipe updates

views/productform.blade.php
=> fix product shopping location for edits

helpers/PrerequisiteChecker.php
=> Added SQLite check for #805

helpers/UrlManager.php
=> Revert "Fix base path computation when running in subdirectory"

services/DatabaseMigrationService.php
=> Run database-Migrations in right order

controllers/FilesApiController.php, localization/userfield_types.pot, migrations/0112.sql, public/js/extensions.js, public/viewjs/components/userfieldsform.js, public/viewjs/equipmentform.js, routes.php, services/UserfieldsService.php, views/components/userfields_tbody.blade.php, views/components/userfieldsform.blade.php
I added a new userfield-type "file", which allows to add a file to an object.
Files are uploaded via FilesApiController and shown as a link in tables.
I also added a new non-api-route to view the file, to show a human readable name, and to get a "normal" error page (instead of JSON).
Related to #262 and #441
=> Add user-field-type "file"

controllers/StockApiController.php, public/js/grocy_dbchangedhandling.js, public/viewjs/consume.js, public/viewjs/recipeform.js, public/viewjs/shoppinglistitemform.js, services/RecipesService.php, services/StockService.php, views/components/locationpicker.blade.php, views/consume.blade.php, views/equipment.blade.php, views/layout/default.blade.php, views/products.blade.php, views/shoppinglist.blade.php, views/shoppinglistitemform.blade.php
Some bug-fixes and enhancements - see commit messages for details.
=> Improvements

views/stockoverview.blade.php
=> fix expiring filter

public/viewjs/components/productcard.js, public/viewjs/purchase.js
Price calculations were not correct in Purchase page and last price was not initialized correctly which was most likely resolved in my other wip branch.
This fixes it for master.
=> fix for price and total price

public/css/grocy_night_mode.css
This fixes a few lines of white when in night mode.
This change was done from a tablet, I can redo this commit properly on a computer when I get back home if needed. This just really annoyed me ;)
=> Fix night mode

public/viewjs/components/productcard.js, views/components/productcard.blade.php
Add button on product card to go to the stock entries for the product
=> stock entries button on product card

services/StockService.php
missing parameter - if null just uses product detail information for AddProduct
=> inventory fix for quFactorPurchaseToStock - defaults to product details

controllers/StockApiController.php, localization/strings.pot, public/viewjs/inventory.js, services/StockService.php, views/inventory.blade.php, views/stocksettings.blade.php
Allow added inventory to set purchased date with same permissions as on the purchase tab.
=> Add purchased date to inventory

public/viewjs/calendar.js, public/viewjs/mealplan.js
Hey,
I removed that resize event as it get's thrown every time you scroll on a mobile device. Which prevented me from actually viewing the list view of the calender on mobile devices.
Let me know if you think it is still needed tho!
~Cheers
=> Removing of resize event

views/shoppinglist.blade.php
added `>` on line 314 otherwise the header was not showed correctly.
There exists still a issue that the header is not aligned correctly with the rest of the table, but I didn't find a solution. Maybe you know what's wrong with it
=> fix missing >

helpers/PrerequisiteChecker.php
=> Added ctype requirement to PrerequisiteChecker

app.php, helpers/ConfigurationValidator.php
Adds a class similar to PrerequisiteChecker that checks if the config.php does not contain any invalid entries (not all entries are checked, only the ones that are most likely to be invalid).
Related to issue #1206
=> Added configuration validator class

public/viewjs/shoppinglist.js
This removes the backdrop before printing
=> Remove backdrop when printing, fix for #1271

public/css/grocy_night_mode.css
=> Night mode improvements

views/recipes.blade.php
=> Hide unsuitable fields from printed recipe pages

README.md
… or do you want me to capitalize both occurances of windows (=> Windows)?
=> Fix typo :)

public/css/grocy_night_mode.css, public/js/extensions.js
My PR got merged overnight (thanks!) but there was still a bit more stuff for me to do. This adds some of that.
Old:
New:
Old:
New:
Old:
New:
(Manually changed)
Old:
New:
Old (that's the version in my last pr):
New:
Don't worry about my API key, they just say "Hi"
Old:
New:
=> More night mode improvements

services/StockService.php
Enforce only PRODUCT grocycodes in GetProductIdFromBarcode (fixes: #1580 )
=> fix: confirm grocycode is of PRODUCT type in GetProductIdFromBarcode

public/viewjs/purchase.js, services/StockService.php
Not yet tested, but I'm about to try it!
=> StockService: Set the product's bestBeforeDate to the freezer date if it is being purchased to a freezer

public/viewjs/batteryform.js
=> Fixed battery label printing

migrations/0203.sql
As I wrote in https://github.com/grocy/grocy/pull/2056#issuecomment-1336459947, the query from the #2056 has a problem in which it would not return any rows for products to which only default conversions apply.
This change makes this work and also subsumes the product-to-product conversion with a factor of 1.0 of [daa0a59](https://github.com/grocy/grocy/commit/daa0a59c5f07b24526a55cb9bf40f29fffd431be#diff-790995ae53772a2f70114217da92c75a9bb6d027099fd7a04543f7d2de699c72R175-R189).
=> Fix quantity_unit_conversions_resolved view

config-dist.php, controllers/SystemController.php, routes.php, views/layout/default.blade.php
=> Add Sub feature flag FEATURE_FLAG_RECIPES_MEALPLAN

views/layout/default.blade.php
Add `fa-fw` class to all side navigation icons to make them the same width.
=> Optimize sidebar icon spacing

controllers/StockReportsController.php, public/viewjs/stockreportspendings.js, views/stockreportspendings.blade.php
Use left (outer) join when connecting product to optional product group. Resolves #2431.
=> Fix blank/missing items in spending report

changelog/75_UNRELEASED_xxxx-xx-xx.md, controllers/BatteriesController.php, grocy.openapi.json, public/viewjs/batterytracking.js, views/batteriesjournal.blade.php, views/batterytracking.blade.php
Shamelessly copied from chores_log.
References #2437
=> Add userfields to battery charge cycle tracking

changelog/75_UNRELEASED_xxxx-xx-xx.md, views/layout/default.blade.php
Untangled it from the other pull request.
=> Align settings (wrench) menu entries

changelog/76_UNRELEASED_xxxx-xx-xx.md, public/viewjs/productform.js
Copy pasted a bit, again. Couldn't find a ticket for that, so no reference.
=> Also copy treat_opened_as_out_of_stock when copying a product

config-dist.php, controllers/BatteriesApiController.php, controllers/ChoresApiController.php, controllers/RecipesApiController.php, controllers/StockApiController.php, services/StockService.php
Added a flag allowing to append details to the webhook body sent to label printers.
This would close #2318
=> Added option to include details in the webhook sent to label printers

README.md, config-dist.php, migrations/0253.sql, package.json, public/css/grocy.css, public/viewjs/components/camerabarcodescanner.js, views/components/camerabarcodescanner.blade.php, views/layout/default.blade.php, yarn.lock
Replaced Quagga2 barcode scanner with ZXing library.
Fixes #2705
=> Replaced barcode scanning library with ZXing
