grocy/grocy

- views/quantityunits.blade.php
The "Add" button was not translated in the 'Quantity units' form.
> FIX: Add missing translation of "Add" button

- views/components/userfieldsform.blade.php
To replace the default string `Product group`
> Use list title when display a user field form

- update.sh
Printed paths did not contain the leading dot for the current directory such that users might be confused by the shown absolute paths (which are not absolute but relative to the script).
> Fixes typo in update.sh

- services/StockService.php
Without this commit, the API returns null instead of 0 when queried for product stock amount
> API: Return stock amount of 0 instead of null, if product is not in stock

- localization/en/strings.po
- localization/strings.pot
- views/productform.blade.php
Given that the location can be set on the purchase page, I thought it was more appropriate to list this as "Default location".
I wasn't sure how the translations work, so if I need to make a change to a different file please let me know.
> Rename location to "Default location" on product page

- public/viewjs/stockoverview.js
I have 143 products and 442 units on stock overview, when I search on my phone the page performance is really poor - this aims to alleviate that.
> Improve mobile performance on stock overview

- public/viewjs/productform.js
PR for issue #419 
This only works when the window was opened by Javascript (eg. from a third party plugin like Barcode Buddy)
Closes #419
> Add GET parameter to close window after product creation

- public/viewjs/recipeform.js
- public/viewjs/recipeposform.js
- views/recipeform.blade.php
- views/recipeposform.blade.php
For the Recipe Ingredient Add and Edit buttons I moved them to instead be bootbox as you have elsewhere.
Edit Ingredient will use the prefill by id. Fixes #475 
I didn't see anywhere else using prefill by name?
Upon success it will currently just reload the page instead of building out a Refresh method.
> Recipe form updates

- public/css/grocy.css
- public/viewjs/shoppinglist.js
I had luck with not enforcing any width, not even 100% and removed the
padding and margin overrides from the shoppinglist.js
I also tested it on a real Android device to be really sure.
> Use full width for compact shopping list

- public/viewjs/mealplan.js
When adding a recipe to the meal plan, I would like the servings to initialize with the base_servings of the recipe.
The new edit recipe function for the meal plan is unaffected and will initialize with the servings set for that meal plan.
> Default initial recipe add for mealplan to use recipe's base_servings

- public/viewjs/mealplan.js
It does not appear that the mealplan recipe_servings is used when adding ingredients to the shopping list or consuming ingredients.
The recipe desired_servings looks to resolve a lot of information that is used when adding ingredients to the shopping list or consuming a recipe ingredients. 
The first commit sets the recipe desired_servings to be the mealplan recipe_servings so that the correct information is resolved.
I fixed the selectedRecipePostion but I did not look elsewhere in the recipe blade for other possible bugs such as if there is a sub recipe.
> Mealplan recipe servings resolution

- services/ChoresService.php
When hitting the API to get a list of all chores, the response does not include the chore name.
I didn't want to then have to iterate through each one to get the name after getting the list of the chores as it could be significantly computationally expensive.
This PR just adds a join on the chores table to include the name of the chore when the list is retrieved.
> Added chore name when getting list of all chores.

- public/css/grocy.css
- views/batteriesoverview.blade.php
- views/choresoverview.blade.php
- views/stockoverview.blade.php
Closes #629 by moving the `consume all` button to the ellipsis menu on small devices.
The display of the ellipsis menu on small devices is more responsive as well.
> 629 Make ellipsis menu in stock overview more responsive

- helpers/PrerequisiteChecker.php
- public/index.php
A lot of people had problems with installing grocy, as it only displays an empty page if there is an error.  This little helper does a quick and cheap check if all dependencies are installed and config.php / config-dist.php exists.
If something is missing, the script stops and outputs an error.
> Check if all dependencies are installed

- helpers/extensions.php
Process `Setting`s from environment and settingoverrides values the same:
* fixes handling strings representing bools from settingoverrides .txt files
* trailing newline characters are now stripped
> Process `Setting`s from environment and settingoverrides values the same

- controllers/StockApiController.php
- controllers/StockController.php
- grocy.openapi.json
- localization/en/strings.po
- localization/fr/strings.po
- localization/strings.pot
- migrations/0099.sql
- public/viewjs/components/productcard.js
- public/viewjs/components/shoppinglocationpicker.js
- public/viewjs/inventory.js
- public/viewjs/purchase.js
- public/viewjs/shoppinglocationform.js
- public/viewjs/shoppinglocations.js
- public/viewjs/stockentryform.js
- routes.php
- services/StockService.php
- views/components/shoppinglocationpicker.blade.php
- views/inventory.blade.php
- views/layout/default.blade.php
- views/purchase.blade.php
- views/shoppinglocationform.blade.php
- views/shoppinglocations.blade.php
- views/stockentries.blade.php
- views/stockentryform.blade.php
This PR adds the concept of shopping location to the price tracking feature.
Tracking price usually makes sense associated to a shopping location, since the price will evolve in that location but will have a different base when you buy it somewhere else. This PR adds this notion to it, and the corresponding charts will now have more than one line to show this difference, allowing the user to chose his/her shopping location depending on the price too.
This fixes https://github.com/grocy/grocy/issues/447
Things to look at specifically:
> Add shopping location for price tracking

- grocy.openapi.json
- migrations/0099.sql
For the `/stock/products/{productId}/locations` request, the amount of stock for each location is returned as well
I added it to the already existing 99.sql - is that the correct way or would it be better to use a 100.sql? The 99.sql is not in the current release.
> Return amount of stock in location API request

- public/viewjs/productform.js
Preset the stock quantity unit with the purchase quantity unit, if the stock quantity unit is unset.
The quantity units are the same in the most cases. So this enhances the input of new products a little bit.
> Preset the stock qu with the purchase qu on new products.

- update.sh
When grocy is installed on a btrfs file system, the `tar` command used in the backup step of the `upgrade.sh` script fails if the tarball is not created first.
The result without creating the tarball looks like this:
```
tar: ./data: file changed as we read it
```
If we use the `touch` command to create a file with the same name as the tarball first, the upgrade works as expected.
> Create the backup tarball explicitly before invoking tar

- public/viewjs/productform.js
The *Save* button didn't become clickable after presetting QU stock Id with QU purchase Id.
> Add missing form validation on presetting QU id stock

- helpers/PrerequisiteChecker.php
It may be worth performing this NodeJS dependency validation check outside of the `grocy` application.
PHP code is well-suited to self-test for presence of configuration file and PHP library dependencies, while other infrastructure may be better suited to check for the presence and integrity of static content.
Previous `grocy` zipfile releases have included the full PHP and NodeJS file dependencies in the expected file path locations.  If that convention continues, then users deploying a simple installation from a release zipfile should be unlikely to encounter situations where PHP requirements are fulfilled and yet NodeJS dependencies are missing.
Fixes #744
> Remove NodeJS dependency check

- controllers/CalendarApiController.php
`PHP Warning:  DateTime::setTimezone() expects parameter 1 to be DateTimeZone, string given in /var/www/grocy/controllers/CalendarApiController.php on line 22`
> Fixed Timezone in CalendarApiController

- public/viewjs/components/productcard.js
- public/viewjs/purchase.js
- views/purchase.blade.php
A number of items to review
- Update products_average_price view with rounding
- Add average price to added to product card
- Recipe costs, use default consume rule which is "First expiring first, then first in first out"
Achieved by updating the recipes_pos_resolved to use the new products_oldest_price view
- Update product details to use products_last_purchased view to reduce db calls
- deprecate products_current_price due to using products_last_purchased and changing recipe_pos_resolved
**update to recipe costs calculation in recipes_pos_resolved**
- when using only_check_single_unit_in_stock, now set the case to use 0 so that the costs is not included in the recipe costs. Logic is, if the product will not be consumed, then why add it to the costs?
- move rp.amount outside of if …
> Purchase Price Hints

- public/js/extensions.js
If a special character like "&" is passed URL encoded, grocy decoded it before parsing. That way if an ampersand was in a variable, the ampersand and everything after was ignored.
To reproduce: https://demo.grocy.info/product/new?closeAfterCreation&prefillname=Ben%20%26%20Jerry%27s%20Glace%20Cookie%20Dough%20Vanille%20500%20ml&prefillbarcode=0076840600021
> Make GetUriParam work with special characters (eg. "&")

- migrations/0102.sql
Reordered weekdays back in ascending order, to ease readability.
Fixed weekday numbers - serious copy-paste fail there.
Order by the next date, rather than the name of the day.
> Fixed fix for #570

- views/choresoverview.blade.php
An ellipsis in software often implies that the element is clickable to get more information.  Changing that to a simple dash symbol makes it more clear that the value is simply undefined and is not a clickable element.
> Change ellipsis to dash

- helpers/UrlManager.php
This is my attempt to fix #944. I tested it with a version of grocy running in the web root and a version running in a subdirectory.
> Fix base path computation when running in subdirectory

- public/index.php
Hi!
I am running multiple instances of grocy to keep track of different households. To make maintenance easier, I wanted to run all instances from the same installation directory and separate the data directories only. Previously the data directory was fixed to the GROCY_DATAPATH constant. This PR allows overriding the default GROCY_DATAPATH location by the FastCGI parameter `GROCY_DATAPATH`. Relative paths are modified and get rooted at the top level grocy installation directory. The previous behaviour is preserved in case the new parameter is absent.
The following example nginx config snippet shows how to run multiple instances.
```nginx
server {
location /instance1/ {
alias /var/www/grocy/;
set $instance instance1;
try_files $uri @grocy;
}
location /instane2/ {
alias /var/www/grocy/; …
```
> Run multi instances by making GROCY_DATAPATH customizable

- localization/strings.pot
- views/locationcontentsheet.blade.php
The ID "Consumend Amount" should fairly obvously be "Consumed Amount" instead.
This was bugging me quite a bit when fooling around in the interface, so here's a PR to fix it!
> WIP: Fix typo on "Consumed Amount" localization string

- controllers/StockController.php
- migrations/0105.sql
- migrations/0106.sql
- services/StockService.php
- views/stockoverview.blade.php
Hi,
I tried to improve the Performance of the "Stock overview" page, and found some improvements:
1) I replaced some of the `FindObjectInArrayByPropertyValue`-calls by getting this values directly in the database query.
This also made the template-code more readable.
2) I optimized the "stock_current"-database-view:
I created 2 indices, and replaced a subquery with a (left-)join.
I'm not sure why, but this combination improved the speed significantly.
stock_current is used often:
I got a speedup from 1.26s to 0.13s on /stock/products #848
The view stock_missing_products, which uses stock_current, is now 25 times faster (from ~1250 ms to ~50ms) on my sample data.
Might be related to #898 (Note that JavaScript ("Datatables") also has some loading time. I think pagination could fix that.)
> Improve Performance

- services/ChoresService.php
Fixes #930 
I think I found the problem:
When determining the next assigned person for a chore, the last "tracked_time" is used.
If you "Track date only", and multiple users execute the chore at one day, it is "undefined" which of these executions is the last one. It seems to be always the first tracked on that date, so the next assigned person is whoever is after the person who first executed it.
That happens also with more than 2 persons. (and is not related to the alphabetically last person).
I fix this by using the last row_created_timestamp to identify the last execution.
Quick Fix: Uncheck the "Track date only" checkbox.
> use last Chore-Log when determining the next assigned person

- public/viewjs/components/productamountpicker.js
Since the value of $('#amount') will be written to the database it should not be locale dependent. This code also limits the result to a maximum of 4 digits but always uses a dot as decimal separator.
> Make product amount picker locale independent

- config-dist.php
- public/viewjs/components/barcodescanner.js
Hello, @berrnd.
This is an initial commit for review and discussion.
When trying to make the barcode scanner work on Grocy on my iPhone, I had to tweak some of the Quagga settings to achieve optimal results, which differ from the default. For example, to me I need to set halfSample to true, patchSize to small and frequency to 5. These took lots of time to tweak, and I thought a PR enabling these configurations on config.php along with numOfWorkers might be valuable to some users. Also, to enhance performance, I added an option to enable/disable the debug options for Quagga.
> Additional configuration options for Quagga2

- services/StockService.php
Using Mark as Open in the stock entry page loses some information if new stock entries are created.
> Include location and shopping_location_id when opening products

- controllers/BaseApiController.php
- controllers/BatteriesApiController.php
- controllers/ChoresApiController.php
- controllers/GenericEntityApiController.php
- controllers/RecipesApiController.php
- controllers/StockApiController.php
- controllers/TasksApiController.php
- controllers/UsersApiController.php
- migrations/0114.sql
- routes.php
- services/BatteriesService.php
- services/ChoresService.php
- services/RecipesService.php
- services/StockService.php
- services/TasksService.php
- services/UsersService.php
- views/batteriesoverview.blade.php
- views/choresoverview.blade.php
- views/stockentries.blade.php
- views/stockoverview.blade.php
- views/tasks.blade.php
I've added a simple generic function for filtering, ordering and pagination for API-Results.
It can be used (only) on a LessQL\Result.
For now, I use it in '/objects/{entity}/search/' and '/recipes/fulfillment'.
Fixes #577 
It uses 4 (optional) Query-Params:
- order   The column to order by
- limit     The maximum count of objects to return
- offset     Number of elements to skip
- query[]    An array of conditions, each of them is a string with:
- a column name
- a comparison operator
- a value to search for
The available comparison operators:
- `=`    equal
- `~`   LIKE
- `<`   less
- `>` greater
- `>=` greater or equal
- `<=` less or equal
All operators can be negated by prepending it with a `!`
Example:
`/api/objects/products/search/?order=name&limit=5&offset=1&query[]=name%3DCho` …
> Filtering of API-Results

- controllers/StockApiController.php
- controllers/StockController.php
- localization/strings.pot
- migrations/0115.sql
- public/viewjs/stockjournalsummary.js
- routes.php
- services/StockService.php
- views/stockjournal.blade.php
- views/stockjournalsummary.blade.php
- views/stockoverview.blade.php
Fixes #827 , #963 , #949 
I've implemented an API for the stock journal, available at `/api/stock/journal`.
For #827 and #949, I added the user to stock_log. The default for the migrations is 'admin'.
I also added a new Page (and API) "stock journal summary", which sums up the amounts grouped by product, user and transaction-type.
> Stock-Journal: API, Summary, Done By

- README.md
- public/js/grocy_clock.js
- public/viewjs/productform.js
- views/productform.blade.php
Detailed descriptions can be found in the corresponding commit messages. To summarize, the following things changed with this PR:
* 6ffad1d  adds instructions how to bootstrap a dev environment
* 2b0208e  fixes the checkbox-behavior for enabling/disabling the header clock
* 007b427: Make sure it's possible to delete and update a product's picture in one go.
* 248852b: Add a `Save & continue` button to product form.
> Adds a few small frontend fixes

- controllers/GenericEntityApiController.php
- public/js/grocy.js
- public/js/grocy_nightmode.js
- public/viewjs/components/datetimepicker.js
- public/viewjs/purchase.js
- services/CalendarService.php
- views/components/locationpicker.blade.php
- views/components/productpicker.blade.php
- views/components/shoppinglocationpicker.blade.php
- views/purchase.blade.php
- 515da5d The datetimepicker is now removed if FEATURE_FLAG_STOCK_BEST_BEFORE_DATE_TRACKING is not set (fixes #997)
- 9f9acb7 `DateTimePicker.SetValue()` did not set the value if the shortcut-checkbox was checked (e.g. "Never expires") - it only cleared the field and the checkbox (caused #997: without FEATURE_FLAG_STOCK_BEST_BEFORE_DATE_TRACKING, the field is set to "Never Expires". When you choose a product with default-best-before-date, the field is cleared/empty and hidden, and the validation failed.)
- ef2e5dd Clicking the whole (highlighted) area in drop downs with checkboxes now toggles the checkbox.
- 50ee248 Night-mode enabling does not need a reload
- Some undefined variables
> Some bug fixes.

- config-dist.php
- controllers/StockApiController.php
- public/viewjs/purchase.js
- public/viewjs/stocksettings.js
- views/purchase.blade.php
- views/stocksettings.blade.php
feature #888
Initial feature request checkin
I did not limit this to GROCY_FEATURE_FLAG_STOCK_BEST_BEFORE_DATE_TRACKING but perhaps it should be?
This might be made a little better by updating the best before date whenever the purchase date is changed?
> add purchased date to purchase

- public/viewjs/manageapikeys.js
> Hi, I just saw that API keys are now scannable with QR codes. Thanks for that!
I tried it on the prerelease demo and I noticed that the QR codes don't contain the API key but the instance URL and key type... Is this intended behaviour?
No.
There were two parameters swapped.
The urls should contain the instance URL and the Key, seperated by a `|`.
I refactored the Code before #986 and it seems that I didn't test enough (I think I only checked that there is a QR-Code).
Sorry.
Fixes #1092
> Fixes #1092: Repair QR-Codes for API-Keys

- public/viewjs/shoppinglist.js
- public/viewjs/shoppinglistform.js
- public/viewjs/shoppinglistitemform.js
- views/shoppinglist.blade.php
This adds an edit button for shopping lists and attempts to use dialogs.
fixes #1091
One note: if you could look into the add product to shopping list it is not refreshing the item list after saving the dialog box.
I'm not sure if you want to just refresh the whole screen or refresh the datatable.
> dialogs for shopping list

- public/viewjs/mealplan.js
Stock name instead of purchase name
I'm not sure if it's the right variable, because there is still a convertion function but this seem better than wrongly displaying the purchase unit name
> Unit stock name in the mealplan

- services/StockService.php
When testing a recipe that produces a product, the new quFactorPurchaseToStock provided an error and just needs to be set to null in the AddProduct method. This allows the self producing product to use the default quFactorPurchaseToStock when a recipe is consumed.
> AddProduct Method Fix For SelfProduction

- controllers/StockController.php
- The recipe dropdown for consume should be limited to normal recipes. Where else should this be considered?
- The transfer page does not need to load recipes.
> limit to normal recipes

- migrations/0106.sql
- migrations/0108.sql
> I have no explanation, but any of the indexes created in that migration made that the stock_current view failed (the column is_aggregated_amount did not work anymore, returned always 0).
I searched for over an hour, but haven't found out what specific thing the problem is, it seems to be the combination of those indexes - strange...
I've found the issue:
is_aggregated_amount is not an aggregated column (not min(), avg(), sum(), etc.),
so sqlite picks a value from one of the rows in the group - from which row is undefined.
The indexes change how the query is executed, which causes sqlite to pick another row.
> Fix is_aggregate_amount always 0 on stock_current

- changelog/60_UNRELEASED_2020-xx-xx.md
I saw that because the syntax hightlighting on GitHub only sees one `code` apostrophe and thus colors the whole following text wrong.
> Correct typo in changelog

- controllers/SystemApiController.php
- grocy.openapi.json
- routes.php
- services/ApplicationService.php
As Grocy is using local time for all database entries, I needed a call to get the server's timezone.
This also outputs local time and UTC and an offset can be applied, which can be useful for external programs.
> Added /system/time API call

- public/viewjs/shoppinglistitemform.js
Now the fields are properly checked and the error does not show up anymore.
The only minor issue is that the save button is disabled if editing a shoppinglist note without a product, but as soon as the note is changed, the save button is enabled again. However as no errormessages are shown and it kind of makes sense that you cannot save the item without any changes first I did not add another validation in this PR.
> Fixed shoppinglist JS, fix for #1289 and #1261

- config-dist.php
- middleware/LdapAuthMiddleware.php
- Changed LDAP authentication to double bind (1st bind with read-only service account, 2nd bind to authenticate user)
- LDAP username attribute defined in config.php
- Added optional LDAP filter in config.php
Tested with Windows 2019 AD (LDAP+LDAPS), OpenLDAP (LDAP) and GLauth (LDAP+LDAPS)
```
// Windows AD LDAP
Setting('LDAP_ADDRESS', 'ldap://winad.windows.ad:389');
Setting('LDAP_BASE_DN', 'DC=windows,DC=ad');
Setting('LDAP_BIND_DN', 'CN=Grocy Bind Account,OU=Service Accounts,DC=windows,DC=ad');
Setting('LDAP_BIND_PW', 'Password1!');
Setting('LDAP_USER_FILTER', '(memberof=CN=Grocy Users,OU=Users,DC=windows,DC=ad)');
Setting('LDAP_UID_ATTR', 'sAMAccountName');
// Windows AD LDAPS
Setting('LDAP_ADDRESS', 'ldaps://winad.windows.ad:636');
Setting('LDAP_BASE_DN', 'DC=windows,DC=ad'); …
```
> Improved support for other LDAP servers

- public/viewjs/components/barcodescanner.js
Hi all,
I was looking for support in managing our medicine cabinet and to track which drugs are available.
In Germany, packages of drugs have also a printed barcode that encodes their PZN number which is some kind of EAN for pharmaceutics. However, this barcode is encoded as Code 39 barcode which is currently not supported by the build-in barcode reader. In this pull request, I have added the support for code 39. 
During my tests, I figured out that (at least for code 39), an error rate is not added for each digit all the time. Thus, the onDetect function did not work (ErrorCount & DecodedCodesCount are both 0, i.e. NaN). Thus, I have extended the if-clause to cover also the case that both counts are 0, but there is a scanned code.
Hopefully, this request is fine so far and gets …
> Added support for Code 39

- helpers/PrerequisiteChecker.php
After installing Grocy on FreeBSD, even with all extensions installed that are listed in REQUIRED_PHP_EXTENSIONS, Grocy still couldn't start. The added 3 PHP Extensions are also needed to run Grocy.
> Extend REQUIRED_PHP_EXTENSIONS check about core extensions

- composer.json
In composer.json it is better not to work with `>=` in PHP. When the next PHP version is released (with breaking changes) there will be problems. `^` is more suitable, because you only allow minor patches here.
I also added a name and a description so the json is valid.
> Change PHP Dependency from >= to ^

- controllers/StockApiController.php
if the stock_entry_id is in the request body use this instead of the stockentry grocycode
this may not be the correct way to interpret this but one of them has to win
> fix: make stockentry grocycodes consume the actual stock entry not the product in general

- views/login.blade.php
The attribute was dropped in 9942a2d.
> Add name to stay_logged_in checkbox

- localization/component_translations.pot
- package.json
- public/js/grocy.js
- public/viewjs/components/batterycard.js
- public/viewjs/components/chorecard.js
- public/viewjs/components/datetimepicker.js
- public/viewjs/components/datetimepicker2.js
- public/viewjs/components/productcard.js
- views/layout/default.blade.php
- views/stockentries.blade.php
- views/stockoverview.blade.php
- yarn.lock
As described in #1685 fuzzy time display is incorrect in Hungarian (and possibly other languages). This PR replaces the timeago package with momentjs inbuilt functionality `fromNow()`.
I also fixed an issue with the relevant table rows where the blade template set the datetime to ` 23:59:59` when no date was provided for the `best_before_date` or `purchased_date` fields. This resulted in an invalid date.
This is my first PR for this repo, please advise if I missed anything or if I should check other things as well.
> Replace Timeago with momentjs

- public/viewjs/stockentries.js
- views/stockentries.blade.php
In the stockentries view the ordering by expiration date, amount, price
and purchase date did not work as expected. b5fc64cf already addressed a
similar issue for other views. This commit now does the same: set
DataTables types on the specific columns.
Since the units being part of the "amount" column break numeric sorting,
this commit adds a "data-order" field for that column, so numeric
sorting can still work. This is done in aligment with the stockoverview
page, that already contains such an entry to facilitate proper sorting.
> Improve sorting for stock entries view

- middleware/LdapAuthMiddleware.php
The LDAP provider used the transmitted POST Value as the username instead of the username attribute. Through this, the username was case-sensitive and for every possibility of mixing the char, a new user was created.
> LDAP: Use UID Attribute instead of POST Value

- config-dist.php
- middleware/ReverseProxyAuthMiddleware.php
This is a modification for ReverseProxyAuthMiddleware in order to support server env variables.
These are more secure than regular headers. An example for authelia running behind nginx would be:
```
[...]
server_name grocy.yourserver
include snippets/authelia.conf;
location / {
include snippets/auth.conf;
try_files $uri /index.php;
}
location ~ \.php$ {
fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
include        fastcgi_params;
fastcgi_param REMOTE_USER $user;
fastcgi_param REMOTE_GROUPS $groups;
fastcgi_param  PATH_INFO        $path_info;
fastcgi_pass unix:/run/php/php7.3-fpm.sock;
}
```
In this case `fastcgi_param REMOTE_USER $user;` would set the env variable REMOTE_USER with the logged in user name
> Added support for reading auth header from env variable

- public/css/grocy.css
Layout settings are hidden in the print dialog when printing a page like the mealplan.
Bootstrap 4 bug https://github.com/twbs/bootstrap/issues/25629
> fix: can't print in landscape

- controllers/StockApiController.php
While playing around with the API, I realised that /stock/products/by-barcode/:grocycode/open (OpenProductByBarcode) ignores the stock_id provided in the barcode.
But [ConsumeProductByBarcode](https://github.com/grocy/grocy/blob/af7de61c43e250bf03f1a3209e96c19c5efa9e9e/controllers/StockApiController.php#L327) does respect the stock_id.
So I compared both functions and adapted OpenProductByBarcode to mimic ConsumeProductByBarcode.
I tested the API afterwards and it works as expected
> Handle stock_id in OpenProductByBarcode

- services/StockService.php
Fixes for losing Note field content when splitting stock entries, either by transfer, consume, opening or undoing transactions... #1961
> Fixes for losing Stock Note field content #1961

- migrations/0203.sql
As discussed in #2039, here's a WIP pull request that adds support for transitive unit conversions to grocy.
When using it, I noticed that floating point inaccuracies may arise.
E.g. referring to the conversions defined in #2039, instead of `2 TL`, the UI will ` 1.9999 TL`.
However, this likely would have happened for a single conversion as well, depending on the factors, as the recipe ingredients are stored internally in the storage unit (?).
Regarding the query, I tried to keep the original one mostly the same and put it in the `single` CTE.
However, I removed the joins with the `quantity_units` table, as those were only used for the names and not relevant for the calculations, and moved them to the final `SELECT`.
When writing this, I thought that the `source` column mostly serves as a …
> Add support for transitive unit conversions

- migrations/0208.sql
This PR proposes the migration discussed in https://github.com/grocy/grocy/pull/2056#issuecomment-1364540297 to address the performance problems raised in #2081.
Notably, as 0229d187aedfe50446ad42887810e70ba0b86109 removed the `qu_factor_purchase_to_stock`, the query could be simplified again, removing the priority system.
The main change, however is the `default_conversions` CTE, which is later used when calculating the transitive hull.
> Add migration for improved quantity_unit_conversions_resolved view

- migrations/0233.sql
During the release of the cache__quantity_unit_conversions_resolved the change on the stock_current view was left out.
> stock_current view now uses cached QUCs -> Recipes consume 50% faster

- public/viewjs/tasks.js
- views/tasks.blade.php
The 'Tasks' view had an empty space for another default filter along the header bar. I have a lot of categories and it simplifies presentation to filter according to the task category without adding a lot of unnecessary clutter to the view.
I would be happy to add this as a configurable option but I wanted to check first whether we could just include it by default. Happy to take feedback or suggestions.
> Added 'category' filter to tasks view.

- grocy.openapi.json
A subset of changes proposed in #2429
- the `ProductDetailsResponse` type contains product_barcodes field. Openapi says that it contains a `ProductBarcode` item while actual type is an array of such items.
- change several occurences of `date-time` to `date` in cases where only date is returned
> Fix data types in opeanapi description

- controllers/FilesApiController.php
Currently, file uploads are buffered in memory. For very large uploads this can cause a memory exhaustion and I noticed the following error:
```text
NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 98566176 bytes) in /var/www/grocy/packages/slim/psr7/src/Stream.php on line 357
```
This pull request changes the logic to stream an upload directly into the target file (using a chunk size of 32 KB). Now the maximum file size is only controlled by the likes of `client_max_body_size` and no longer affected by the PHP `memory_limit`.
Please just let me know if anything shall be revised, or you would like to receive the pull request in a different format.
> Stream uploads to file

- update.sh
By making the date in backup filename ISO 8601 compliant (year-month-day) an alphabetical sort of the backups automatically will be a chronological sort of the backups. This is more convenient.
As the automatic deletion of backups older than 60 days relies on the modified date of the file (and not the filename), this will continue to work without problems.
See also: https://www.xkcd.com/1179/
> Make date in backup filename ISO 8601 compliant

- controllers/StockReportsController.php
- migrations/0239.sql
Possible solution to #2595 which I think achieves what you mentioned in Reddit
> Spontaneously I'd also say self produced products should simply be excluded from that report
The spending report uses the `products_price_history` view. By adding the `transaction_type` to that view, we can exclude the `self-production` transactions from the spending report queries.
I tested the spending report view to check it was working as expected, and the product price history endpoint by visiting the Purchase/Inventory views.
The endpoint that returns the products price history only returns a subset the properties, so there wasn't any change introduced to it. For example, if you go to the inventory and select the produced product, you would still see its price.
```
$rows = …
```
> Exclude self-produced product prices from spending reports

- views/login.blade.php
I noticed this because I'm writing a playwright test for Grocy and the `get_by_label` selector was not working. Now it's working.
> Make labels on login form point to correct inputs

- grocy.openapi.json
While developing a basic application using OpenAPI, I noticed that volatile did not have the correct type.
> fix(openapi): volatile is not an array, it's an object

- services/StockService.php
My external data provider returns image data as a `data:image/png;base64,xxx...` URI instead of a URL.
This PR adds support for handling such case and also provides a mechanism for plug-in writers to return an image even when the image URL is not publicly accessible.
> Support `data:` URI images for external barcode lookup plugins
